application:
  appId: TESTAPP
  assetId: TESTAPP
  sdlcType: EDM
  appType: Webapp
  appName: Vulnapp
  webservice: true
  restApi: true
  microservice: false
  projectLanguage: Java
  platformVersion: Java 8
  buildSystem: Maven
  riskMatrixRevision: Rev2.0
  sourceFilePattern: .*\+\+\+.*(\.java|\.jsp)+.*
  sensitivePackagePattern: .*(\+\+\+.*(com\/scalesec\/vulnado)).*
  fileChangeThreshold: 5
  release: minor
environment:
  scm: github
  scmOwner: meerasubbarao
  scmRepositoryName: vulnapp
  scmBranchName: master
  githubApiUrl: https://api.github.com/repos/
  testDeploymentRoot: "vulnapp"
  imChannelIdentifier: "C015LGE7RRQ"
  imChannel: "slack"
  jiraProjectName: "DEM"
  jiraIssuesQuery: "resolution = \"Unresolved\" AND labels in (Security, Defect)"
